theme: jekyll-theme-minimal

title: [Zylonensender-Numbers]
description: [A short analysis of episode ratings by the zylonensender podcast]
logo: [https://raw.githubusercontent.com/Japhiolite/podcast-stuff/master/imgs/Zylonensender_3000x3000.png]
